# Generated by Django 2.2.13 on 2020-06-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_item_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
