# Generated by Django 2.2.13 on 2020-06-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
