# Generated by Django 2.2.13 on 2020-07-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_remove_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='part',
            field=models.CharField(choices=[('profile', 'PROFILE'), ('contact', 'CONTACT'), ('education', 'EDUCATION'), ('experience', 'EXPERIENCE'), ('interests', 'INTEREST')], default='education', max_length=10),
        ),
    ]
